-- CreateEnum
CREATE TYPE "BoardTag" AS ENUM ('BUSINESS_DEVELOPMENT', 'SALES', 'PRODUCT_DEVELOPMENT', 'ADMINISTRATION', 'CUSTOMER_SUCCESS', 'MARKETING', 'FINANCE', 'RESEARCH');

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "tag" "BoardTag";

